// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
import 'package:tom_reflector/tom_reflector.dart' as ta;
import 'package:reflector_reflection_introduction_sample/catalog.dart' as lib0;

final _classes = <String, ta.ClassDescriptor>{
'package:reflector_reflection_introduction_sample/catalog.dart.Entity': ta.ClassDescriptor(
  name: 'Entity',
  qualifiedName: 'package:reflector_reflection_introduction_sample/catalog.dart.Entity',
  libraryUri: 'package:reflector_reflection_introduction_sample/catalog.dart',
  package: 'reflector_reflection_introduction_sample',
  annotations: const [],
  typeParameters: const [],
  isAbstract: false,
  isSealed: false,
  isFinal: false,
  isBase: false,
  isInterface: false,
  isMixinClass: false,
  methods: const {},
  staticMethods: const {},
  fields: <String, ta.FieldDescriptor>{
  'table': ta.FieldDescriptor(
    name: 'table',
    typeQualifiedName: 'dart:core.String',
    isStatic: false,
    isFinal: true,
    isConst: false,
    declaringClassQualifiedName: null,
    annotations: const [],
    getInstance: (Object instance) => (instance as lib0.Entity).table,
    setInstance: null,
    getStatic: null,
    setStatic: null,
  ),
  },
  staticFields: const {},
  getters: const {},
  staticGetters: const {},
  setters: const {},
  staticSetters: const {},
  superclassQualifiedName: 'dart:core.Object',
  interfaceQualifiedNames: const [],
  mixinQualifiedNames: const [],
  appliedExtensionQualifiedNames: const [],
  constructors: <String, ta.ConstructorDescriptor>{
    'new': ta.ConstructorDescriptor(
      name: 'new',
      isFactory: false,
      parameters: [
ta.ParameterDescriptor(name: 'table',typeQualifiedName: 'dart:core.String',isRequired: true,isNamed: false,isPositional: true,hasDefaultValue: false,defaultValue: null,annotations: const [],)
],
      annotations: const [],
      invoke: (List<dynamic> positional, Map<Symbol, dynamic> named) => Function.apply(lib0.Entity.new, positional, named),
    ),
  },
  isInstance: (Object instance) => instance is lib0.Entity,
),
'package:reflector_reflection_introduction_sample/catalog.dart.Product': ta.ClassDescriptor(
  name: 'Product',
  qualifiedName: 'package:reflector_reflection_introduction_sample/catalog.dart.Product',
  libraryUri: 'package:reflector_reflection_introduction_sample/catalog.dart',
  package: 'reflector_reflection_introduction_sample',
  annotations: [
ta.AnnotationDescriptor(name: 'Entity',qualifiedName: 'package:reflector_reflection_introduction_sample/catalog.dart.Entity',positionalArguments: <Object?>[],namedArguments: const <String, Object?>{},)
],
  typeParameters: const [],
  isAbstract: false,
  isSealed: false,
  isFinal: false,
  isBase: false,
  isInterface: false,
  isMixinClass: false,
  methods: <String, ta.MethodDescriptor>{
  'discountedPrice': ta.MethodDescriptor(
    name: 'discountedPrice',
    isStatic: false,
    isAbstract: false,
    isOperator: false,
    returnTypeQualifiedName: 'dart:core.double',
    declaringClassQualifiedName: null,
    typeParameters: const [],
    parameters: [
ta.ParameterDescriptor(name: 'pct',typeQualifiedName: 'dart:core.double',isRequired: true,isNamed: false,isPositional: true,hasDefaultValue: false,defaultValue: null,annotations: const [],)
],
    annotations: const [],
    invokeOn: (Object instance, List<dynamic> positional, Map<Symbol, dynamic> named) => Function.apply((instance as lib0.Product).discountedPrice, positional, named),
    invokeStatic: null,
  ),
  'toString': ta.MethodDescriptor(
    name: 'toString',
    isStatic: false,
    isAbstract: false,
    isOperator: false,
    returnTypeQualifiedName: 'dart:core.String',
    declaringClassQualifiedName: null,
    typeParameters: const [],
    parameters: const [],
    annotations: [
ta.AnnotationDescriptor(name: 'override',qualifiedName: 'dart:core.override',positionalArguments: <Object?>[],namedArguments: const <String, Object?>{},)
],
    invokeOn: (Object instance, List<dynamic> positional, Map<Symbol, dynamic> named) => Function.apply((instance as lib0.Product).toString, positional, named),
    invokeStatic: null,
  ),
  },
  staticMethods: const {},
  fields: <String, ta.FieldDescriptor>{
  'sku': ta.FieldDescriptor(
    name: 'sku',
    typeQualifiedName: 'dart:core.String',
    isStatic: false,
    isFinal: true,
    isConst: false,
    declaringClassQualifiedName: null,
    annotations: const [],
    getInstance: (Object instance) => (instance as lib0.Product).sku,
    setInstance: null,
    getStatic: null,
    setStatic: null,
  ),
  'name': ta.FieldDescriptor(
    name: 'name',
    typeQualifiedName: 'dart:core.String',
    isStatic: false,
    isFinal: false,
    isConst: false,
    declaringClassQualifiedName: null,
    annotations: const [],
    getInstance: (Object instance) => (instance as lib0.Product).name,
    setInstance: (Object instance, Object? value) { (instance as lib0.Product).name = value as dynamic; return null; },
    getStatic: null,
    setStatic: null,
  ),
  'price': ta.FieldDescriptor(
    name: 'price',
    typeQualifiedName: 'dart:core.double',
    isStatic: false,
    isFinal: false,
    isConst: false,
    declaringClassQualifiedName: null,
    annotations: const [],
    getInstance: (Object instance) => (instance as lib0.Product).price,
    setInstance: (Object instance, Object? value) { (instance as lib0.Product).price = value as dynamic; return null; },
    getStatic: null,
    setStatic: null,
  ),
  'stock': ta.FieldDescriptor(
    name: 'stock',
    typeQualifiedName: 'dart:core.int',
    isStatic: false,
    isFinal: false,
    isConst: false,
    declaringClassQualifiedName: null,
    annotations: const [],
    getInstance: (Object instance) => (instance as lib0.Product).stock,
    setInstance: (Object instance, Object? value) { (instance as lib0.Product).stock = value as dynamic; return null; },
    getStatic: null,
    setStatic: null,
  ),
  'label': ta.FieldDescriptor(
    name: 'label',
    typeQualifiedName: 'dart:core.String',
    isStatic: false,
    isFinal: false,
    isConst: false,
    declaringClassQualifiedName: null,
    annotations: const [],
    getInstance: (Object instance) => (instance as lib0.Product).label,
    setInstance: null,
    getStatic: null,
    setStatic: null,
  ),
  },
  staticFields: const {},
  getters: const {},
  staticGetters: const {},
  setters: const {},
  staticSetters: const {},
  superclassQualifiedName: 'dart:core.Object',
  interfaceQualifiedNames: const [],
  mixinQualifiedNames: const [],
  appliedExtensionQualifiedNames: const [],
  constructors: <String, ta.ConstructorDescriptor>{
    'new': ta.ConstructorDescriptor(
      name: 'new',
      isFactory: false,
      parameters: [
ta.ParameterDescriptor(name: 'sku',typeQualifiedName: 'dart:core.String',isRequired: true,isNamed: true,isPositional: false,hasDefaultValue: false,defaultValue: null,annotations: const [],),
ta.ParameterDescriptor(name: 'name',typeQualifiedName: 'dart:core.String',isRequired: false,isNamed: true,isPositional: false,hasDefaultValue: true,defaultValue: '\'\'',annotations: const [],),
ta.ParameterDescriptor(name: 'price',typeQualifiedName: 'dart:core.double',isRequired: false,isNamed: true,isPositional: false,hasDefaultValue: true,defaultValue: '0',annotations: const [],),
ta.ParameterDescriptor(name: 'stock',typeQualifiedName: 'dart:core.int',isRequired: false,isNamed: true,isPositional: false,hasDefaultValue: true,defaultValue: '0',annotations: const [],)
],
      annotations: const [],
      invoke: (List<dynamic> positional, Map<Symbol, dynamic> named) => Function.apply(lib0.Product.new, positional, named),
    ),
    'sample': ta.ConstructorDescriptor(
      name: 'sample',
      isFactory: false,
      parameters: const [],
      annotations: const [],
      invoke: (List<dynamic> positional, Map<Symbol, dynamic> named) => Function.apply(lib0.Product.sample, positional, named),
    ),
  },
  isInstance: (Object instance) => instance is lib0.Product,
),
'package:reflector_reflection_introduction_sample/catalog.dart.Warehouse': ta.ClassDescriptor(
  name: 'Warehouse',
  qualifiedName: 'package:reflector_reflection_introduction_sample/catalog.dart.Warehouse',
  libraryUri: 'package:reflector_reflection_introduction_sample/catalog.dart',
  package: 'reflector_reflection_introduction_sample',
  annotations: [
ta.AnnotationDescriptor(name: 'Entity',qualifiedName: 'package:reflector_reflection_introduction_sample/catalog.dart.Entity',positionalArguments: <Object?>[],namedArguments: const <String, Object?>{},)
],
  typeParameters: const [],
  isAbstract: false,
  isSealed: false,
  isFinal: false,
  isBase: false,
  isInterface: false,
  isMixinClass: false,
  methods: <String, ta.MethodDescriptor>{
  'receive': ta.MethodDescriptor(
    name: 'receive',
    isStatic: false,
    isAbstract: false,
    isOperator: false,
    returnTypeQualifiedName: 'void',
    declaringClassQualifiedName: null,
    typeParameters: const [],
    parameters: [
ta.ParameterDescriptor(name: 'units',typeQualifiedName: 'dart:core.int',isRequired: true,isNamed: false,isPositional: true,hasDefaultValue: false,defaultValue: null,annotations: const [],)
],
    annotations: const [],
    invokeOn: (Object instance, List<dynamic> positional, Map<Symbol, dynamic> named) => Function.apply((instance as lib0.Warehouse).receive, positional, named),
    invokeStatic: null,
  ),
  },
  staticMethods: const {},
  fields: <String, ta.FieldDescriptor>{
  'code': ta.FieldDescriptor(
    name: 'code',
    typeQualifiedName: 'dart:core.String',
    isStatic: false,
    isFinal: true,
    isConst: false,
    declaringClassQualifiedName: null,
    annotations: const [],
    getInstance: (Object instance) => (instance as lib0.Warehouse).code,
    setInstance: null,
    getStatic: null,
    setStatic: null,
  ),
  'capacity': ta.FieldDescriptor(
    name: 'capacity',
    typeQualifiedName: 'dart:core.int',
    isStatic: false,
    isFinal: false,
    isConst: false,
    declaringClassQualifiedName: null,
    annotations: const [],
    getInstance: (Object instance) => (instance as lib0.Warehouse).capacity,
    setInstance: (Object instance, Object? value) { (instance as lib0.Warehouse).capacity = value as dynamic; return null; },
    getStatic: null,
    setStatic: null,
  ),
  'isFull': ta.FieldDescriptor(
    name: 'isFull',
    typeQualifiedName: 'dart:core.bool',
    isStatic: false,
    isFinal: false,
    isConst: false,
    declaringClassQualifiedName: null,
    annotations: const [],
    getInstance: (Object instance) => (instance as lib0.Warehouse).isFull,
    setInstance: null,
    getStatic: null,
    setStatic: null,
  ),
  },
  staticFields: const {},
  getters: const {},
  staticGetters: const {},
  setters: const {},
  staticSetters: const {},
  superclassQualifiedName: 'dart:core.Object',
  interfaceQualifiedNames: const [],
  mixinQualifiedNames: const [],
  appliedExtensionQualifiedNames: const [],
  constructors: <String, ta.ConstructorDescriptor>{
    'new': ta.ConstructorDescriptor(
      name: 'new',
      isFactory: false,
      parameters: [
ta.ParameterDescriptor(name: 'code',typeQualifiedName: 'dart:core.String',isRequired: true,isNamed: false,isPositional: true,hasDefaultValue: false,defaultValue: null,annotations: const [],),
ta.ParameterDescriptor(name: 'capacity',typeQualifiedName: 'dart:core.int',isRequired: false,isNamed: true,isPositional: false,hasDefaultValue: true,defaultValue: '100',annotations: const [],)
],
      annotations: const [],
      invoke: (List<dynamic> positional, Map<Symbol, dynamic> named) => Function.apply(lib0.Warehouse.new, positional, named),
    ),
  },
  isInstance: (Object instance) => instance is lib0.Warehouse,
),
};
final _enums = <String, ta.MemberContainerDescriptor>{
'package:reflector_reflection_introduction_sample/catalog.dart.Availability': ta.MemberContainerDescriptor(
  kind: ta.TypeKind.enumType,
  name: 'Availability',
  qualifiedName: 'package:reflector_reflection_introduction_sample/catalog.dart.Availability',
  libraryUri: 'package:reflector_reflection_introduction_sample/catalog.dart',
  package: 'reflector_reflection_introduction_sample',
  annotations: const [],
  typeParameters: const [],
  methods: const {},
  staticMethods: const {},
  fields: const {},
  staticFields: const {},
  getters: const {},
  staticGetters: const {},
  setters: const {},
  staticSetters: const {},
),
};
final _mixins = <String, ta.MemberContainerDescriptor>{
};
final _extensions = <String, ta.ExtensionDescriptor>{
};
final _extensionTypes = <String, ta.MemberContainerDescriptor>{
};
final _typeAliases = <String, ta.TypeAliasDescriptor>{
};
final _globals = <String, ta.GlobalDescriptor>{
  'package:reflector_reflection_introduction_sample/catalog.dart.catalogVersion': ta.GlobalDescriptor(
    kind: ta.GlobalKind.function,
    name: 'catalogVersion',
    qualifiedName: 'package:reflector_reflection_introduction_sample/catalog.dart.catalogVersion',
    libraryUri: 'package:reflector_reflection_introduction_sample/catalog.dart',
    package: 'reflector_reflection_introduction_sample',
    typeQualifiedName: 'dart:core.int',
    annotations: const [],
    invokeFunction: (List<dynamic> positional, Map<Symbol, dynamic> named) => Function.apply(lib0.catalogVersion, positional, named),
  ),

};
final reflectionApi = ta.ReflectionApi(
  classesByQualifiedName: _classes,
  enumsByQualifiedName: _enums,
  mixinsByQualifiedName: _mixins,
  extensionsByQualifiedName: _extensions,
  extensionTypesByQualifiedName: _extensionTypes,
  typeAliasesByQualifiedName: _typeAliases,
  globalsByQualifiedName: _globals,
);
