// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
import 'package:tom_reflector/tom_reflector.dart' as ta;
import 'package:reflector_reflection_advanced_sample/store.dart' as lib0;

final _classes = <String, ta.ClassDescriptor>{
'package:reflector_reflection_advanced_sample/store.dart.Auditable': ta.ClassDescriptor(
  name: 'Auditable',
  qualifiedName: 'package:reflector_reflection_advanced_sample/store.dart.Auditable',
  libraryUri: 'package:reflector_reflection_advanced_sample/store.dart',
  package: 'reflector_reflection_advanced_sample',
  annotations: const [],
  typeParameters: const [],
  isAbstract: true,
  isSealed: false,
  isFinal: false,
  isBase: false,
  isInterface: false,
  isMixinClass: false,
  methods: <String, ta.MethodDescriptor>{
  'auditFields': ta.MethodDescriptor(
    name: 'auditFields',
    isStatic: false,
    isAbstract: true,
    isOperator: false,
    returnTypeQualifiedName: 'dart:core.Map',
    declaringClassQualifiedName: null,
    typeParameters: const [],
    parameters: const [],
    annotations: const [],
    invokeOn: null,
    invokeStatic: null,
  ),
  },
  staticMethods: const {},
  fields: const {},
  staticFields: const {},
  getters: const {},
  staticGetters: const {},
  setters: const {},
  staticSetters: const {},
  superclassQualifiedName: 'dart:core.Object',
  interfaceQualifiedNames: const [],
  mixinQualifiedNames: const [],
  appliedExtensionQualifiedNames: const [],
  constructors: <String, ta.ConstructorDescriptor>{
    'new': ta.ConstructorDescriptor(
      name: 'new',
      isFactory: false,
      parameters: const [],
      annotations: const [],
      invoke: null,
    ),
  },
  isInstance: (Object instance) => instance is lib0.Auditable,
),
'package:reflector_reflection_advanced_sample/store.dart.Entity': ta.ClassDescriptor(
  name: 'Entity',
  qualifiedName: 'package:reflector_reflection_advanced_sample/store.dart.Entity',
  libraryUri: 'package:reflector_reflection_advanced_sample/store.dart',
  package: 'reflector_reflection_advanced_sample',
  annotations: const [],
  typeParameters: const [],
  isAbstract: true,
  isSealed: false,
  isFinal: false,
  isBase: false,
  isInterface: false,
  isMixinClass: false,
  methods: <String, ta.MethodDescriptor>{
  'baseFields': ta.MethodDescriptor(
    name: 'baseFields',
    isStatic: false,
    isAbstract: false,
    isOperator: false,
    returnTypeQualifiedName: 'dart:core.Map',
    declaringClassQualifiedName: null,
    typeParameters: const [],
    parameters: const [],
    annotations: const [],
    invokeOn: (Object instance, List<dynamic> positional, Map<Symbol, dynamic> named) => Function.apply((instance as lib0.Entity).baseFields, positional, named),
    invokeStatic: null,
  ),
  },
  staticMethods: <String, ta.MethodDescriptor>{
  'describe': ta.MethodDescriptor(
    name: 'describe',
    isStatic: true,
    isAbstract: false,
    isOperator: false,
    returnTypeQualifiedName: 'dart:core.String',
    declaringClassQualifiedName: null,
    typeParameters: const [],
    parameters: const [],
    annotations: const [],
    invokeOn: null,
    invokeStatic: (List<dynamic> positional, Map<Symbol, dynamic> named) => Function.apply(lib0.Entity.describe, positional, named),
  ),
  },
  fields: <String, ta.FieldDescriptor>{
  'id': ta.FieldDescriptor(
    name: 'id',
    typeQualifiedName: 'dart:core.String',
    isStatic: false,
    isFinal: true,
    isConst: false,
    declaringClassQualifiedName: null,
    annotations: const [],
    getInstance: (Object instance) => (instance as lib0.Entity).id,
    setInstance: null,
    getStatic: null,
    setStatic: null,
  ),
  'kind': ta.FieldDescriptor(
    name: 'kind',
    typeQualifiedName: 'dart:core.String',
    isStatic: false,
    isFinal: false,
    isConst: false,
    declaringClassQualifiedName: null,
    annotations: const [],
    getInstance: (Object instance) => (instance as lib0.Entity).kind,
    setInstance: null,
    getStatic: null,
    setStatic: null,
  ),
  },
  staticFields: <String, ta.FieldDescriptor>{
  'schemaVersion': ta.FieldDescriptor(
    name: 'schemaVersion',
    typeQualifiedName: 'dart:core.int',
    isStatic: true,
    isFinal: false,
    isConst: false,
    declaringClassQualifiedName: null,
    annotations: const [],
    getInstance: null,
    setInstance: null,
    getStatic: () => lib0.Entity.schemaVersion,
    setStatic: (Object? value) { lib0.Entity.schemaVersion = value as dynamic; return null; },
  ),
  },
  getters: const {},
  staticGetters: const {},
  setters: const {},
  staticSetters: const {},
  superclassQualifiedName: 'dart:core.Object',
  interfaceQualifiedNames: const [],
  mixinQualifiedNames: const [],
  appliedExtensionQualifiedNames: const [],
  constructors: <String, ta.ConstructorDescriptor>{
    'new': ta.ConstructorDescriptor(
      name: 'new',
      isFactory: false,
      parameters: [
ta.ParameterDescriptor(name: 'id',typeQualifiedName: 'dart:core.String',isRequired: true,isNamed: false,isPositional: true,hasDefaultValue: false,defaultValue: null,annotations: const [],)
],
      annotations: const [],
      invoke: null,
    ),
  },
  isInstance: (Object instance) => instance is lib0.Entity,
),
'package:reflector_reflection_advanced_sample/store.dart.Order': ta.ClassDescriptor(
  name: 'Order',
  qualifiedName: 'package:reflector_reflection_advanced_sample/store.dart.Order',
  libraryUri: 'package:reflector_reflection_advanced_sample/store.dart',
  package: 'reflector_reflection_advanced_sample',
  annotations: [
ta.AnnotationDescriptor(name: 'Persisted',qualifiedName: 'package:reflector_reflection_advanced_sample/store.dart.Persisted',positionalArguments: <Object?>[],namedArguments: const <String, Object?>{},)
],
  typeParameters: const [],
  isAbstract: false,
  isSealed: false,
  isFinal: false,
  isBase: false,
  isInterface: false,
  isMixinClass: false,
  methods: <String, ta.MethodDescriptor>{
  'toString': ta.MethodDescriptor(
    name: 'toString',
    isStatic: false,
    isAbstract: false,
    isOperator: false,
    returnTypeQualifiedName: 'dart:core.String',
    declaringClassQualifiedName: null,
    typeParameters: const [],
    parameters: const [],
    annotations: [
ta.AnnotationDescriptor(name: 'override',qualifiedName: 'dart:core.override',positionalArguments: <Object?>[],namedArguments: const <String, Object?>{},)
],
    invokeOn: (Object instance, List<dynamic> positional, Map<Symbol, dynamic> named) => Function.apply((instance as lib0.Order).toString, positional, named),
    invokeStatic: null,
  ),
  'baseFields': ta.MethodDescriptor(
    name: 'baseFields',
    isStatic: false,
    isAbstract: false,
    isOperator: false,
    returnTypeQualifiedName: 'dart:core.Map',
    declaringClassQualifiedName: 'package:reflector_reflection_advanced_sample/store.dart.Entity',
    typeParameters: const [],
    parameters: const [],
    annotations: const [],
    invokeOn: (Object instance, List<dynamic> positional, Map<Symbol, dynamic> named) => Function.apply((instance as lib0.Order).baseFields, positional, named),
    invokeStatic: null,
  ),
  },
  staticMethods: const {},
  fields: <String, ta.FieldDescriptor>{
  'total': ta.FieldDescriptor(
    name: 'total',
    typeQualifiedName: 'dart:core.double',
    isStatic: false,
    isFinal: false,
    isConst: false,
    declaringClassQualifiedName: null,
    annotations: const [],
    getInstance: (Object instance) => (instance as lib0.Order).total,
    setInstance: (Object instance, Object? value) { (instance as lib0.Order).total = value as dynamic; return null; },
    getStatic: null,
    setStatic: null,
  ),
  'epochMillis': ta.FieldDescriptor(
    name: 'epochMillis',
    typeQualifiedName: 'dart:core.int',
    isStatic: false,
    isFinal: true,
    isConst: false,
    declaringClassQualifiedName: null,
    annotations: [
ta.AnnotationDescriptor(name: 'override',qualifiedName: 'dart:core.override',positionalArguments: <Object?>[],namedArguments: const <String, Object?>{},)
],
    getInstance: (Object instance) => (instance as lib0.Order).epochMillis,
    setInstance: null,
    getStatic: null,
    setStatic: null,
  ),
  'kind': ta.FieldDescriptor(
    name: 'kind',
    typeQualifiedName: 'dart:core.String',
    isStatic: false,
    isFinal: false,
    isConst: false,
    declaringClassQualifiedName: null,
    annotations: const [],
    getInstance: (Object instance) => (instance as lib0.Order).kind,
    setInstance: null,
    getStatic: null,
    setStatic: null,
  ),
  'id': ta.FieldDescriptor(
    name: 'id',
    typeQualifiedName: 'dart:core.String',
    isStatic: false,
    isFinal: true,
    isConst: false,
    declaringClassQualifiedName: 'package:reflector_reflection_advanced_sample/store.dart.Entity',
    annotations: const [],
    getInstance: (Object instance) => (instance as lib0.Order).id,
    setInstance: null,
    getStatic: null,
    setStatic: null,
  ),
  'isoDate': ta.FieldDescriptor(
    name: 'isoDate',
    typeQualifiedName: 'dart:core.String',
    isStatic: false,
    isFinal: false,
    isConst: false,
    declaringClassQualifiedName: 'package:reflector_reflection_advanced_sample/store.dart.Timestamped',
    annotations: const [],
    getInstance: (Object instance) => (instance as lib0.Order).isoDate,
    setInstance: null,
    getStatic: null,
    setStatic: null,
  ),
  },
  staticFields: <String, ta.FieldDescriptor>{
  'table': ta.FieldDescriptor(
    name: 'table',
    typeQualifiedName: 'dart:core.String',
    isStatic: true,
    isFinal: false,
    isConst: true,
    declaringClassQualifiedName: null,
    annotations: const [],
    getInstance: null,
    setInstance: null,
    getStatic: () => lib0.Order.table,
    setStatic: null,
  ),
  },
  getters: const {},
  staticGetters: const {},
  setters: const {},
  staticSetters: const {},
  superclassQualifiedName: 'package:reflector_reflection_advanced_sample/store.dart.Entity',
  interfaceQualifiedNames: const [],
  mixinQualifiedNames: <String>['package:reflector_reflection_advanced_sample/store.dart.Timestamped'],
  appliedExtensionQualifiedNames: const [],
  constructors: <String, ta.ConstructorDescriptor>{
    'new': ta.ConstructorDescriptor(
      name: 'new',
      isFactory: false,
      parameters: [
ta.ParameterDescriptor(name: 'id',typeQualifiedName: 'dart:core.String',isRequired: true,isNamed: true,isPositional: false,hasDefaultValue: false,defaultValue: null,annotations: const [],),
ta.ParameterDescriptor(name: 'total',typeQualifiedName: 'dart:core.double',isRequired: true,isNamed: true,isPositional: false,hasDefaultValue: false,defaultValue: null,annotations: const [],),
ta.ParameterDescriptor(name: 'epochMillis',typeQualifiedName: 'dart:core.int',isRequired: true,isNamed: true,isPositional: false,hasDefaultValue: false,defaultValue: null,annotations: const [],)
],
      annotations: const [],
      invoke: (List<dynamic> positional, Map<Symbol, dynamic> named) => Function.apply(lib0.Order.new, positional, named),
    ),
  },
  isInstance: (Object instance) => instance is lib0.Order,
),
'package:reflector_reflection_advanced_sample/store.dart.Persisted': ta.ClassDescriptor(
  name: 'Persisted',
  qualifiedName: 'package:reflector_reflection_advanced_sample/store.dart.Persisted',
  libraryUri: 'package:reflector_reflection_advanced_sample/store.dart',
  package: 'reflector_reflection_advanced_sample',
  annotations: const [],
  typeParameters: const [],
  isAbstract: false,
  isSealed: false,
  isFinal: false,
  isBase: false,
  isInterface: false,
  isMixinClass: false,
  methods: const {},
  staticMethods: const {},
  fields: <String, ta.FieldDescriptor>{
  'table': ta.FieldDescriptor(
    name: 'table',
    typeQualifiedName: 'dart:core.String',
    isStatic: false,
    isFinal: true,
    isConst: false,
    declaringClassQualifiedName: null,
    annotations: const [],
    getInstance: (Object instance) => (instance as lib0.Persisted).table,
    setInstance: null,
    getStatic: null,
    setStatic: null,
  ),
  },
  staticFields: const {},
  getters: const {},
  staticGetters: const {},
  setters: const {},
  staticSetters: const {},
  superclassQualifiedName: 'dart:core.Object',
  interfaceQualifiedNames: const [],
  mixinQualifiedNames: const [],
  appliedExtensionQualifiedNames: const [],
  constructors: <String, ta.ConstructorDescriptor>{
    'new': ta.ConstructorDescriptor(
      name: 'new',
      isFactory: false,
      parameters: [
ta.ParameterDescriptor(name: 'table',typeQualifiedName: 'dart:core.String',isRequired: true,isNamed: false,isPositional: true,hasDefaultValue: false,defaultValue: null,annotations: const [],)
],
      annotations: const [],
      invoke: (List<dynamic> positional, Map<Symbol, dynamic> named) => Function.apply(lib0.Persisted.new, positional, named),
    ),
  },
  isInstance: (Object instance) => instance is lib0.Persisted,
),
'package:reflector_reflection_advanced_sample/store.dart.User': ta.ClassDescriptor(
  name: 'User',
  qualifiedName: 'package:reflector_reflection_advanced_sample/store.dart.User',
  libraryUri: 'package:reflector_reflection_advanced_sample/store.dart',
  package: 'reflector_reflection_advanced_sample',
  annotations: [
ta.AnnotationDescriptor(name: 'Persisted',qualifiedName: 'package:reflector_reflection_advanced_sample/store.dart.Persisted',positionalArguments: <Object?>[],namedArguments: const <String, Object?>{},)
],
  typeParameters: const [],
  isAbstract: false,
  isSealed: false,
  isFinal: false,
  isBase: false,
  isInterface: false,
  isMixinClass: false,
  methods: <String, ta.MethodDescriptor>{
  'recordLogin': ta.MethodDescriptor(
    name: 'recordLogin',
    isStatic: false,
    isAbstract: false,
    isOperator: false,
    returnTypeQualifiedName: 'void',
    declaringClassQualifiedName: null,
    typeParameters: const [],
    parameters: const [],
    annotations: const [],
    invokeOn: (Object instance, List<dynamic> positional, Map<Symbol, dynamic> named) => Function.apply((instance as lib0.User).recordLogin, positional, named),
    invokeStatic: null,
  ),
  'auditFields': ta.MethodDescriptor(
    name: 'auditFields',
    isStatic: false,
    isAbstract: false,
    isOperator: false,
    returnTypeQualifiedName: 'dart:core.Map',
    declaringClassQualifiedName: null,
    typeParameters: const [],
    parameters: const [],
    annotations: [
ta.AnnotationDescriptor(name: 'override',qualifiedName: 'dart:core.override',positionalArguments: <Object?>[],namedArguments: const <String, Object?>{},)
],
    invokeOn: (Object instance, List<dynamic> positional, Map<Symbol, dynamic> named) => Function.apply((instance as lib0.User).auditFields, positional, named),
    invokeStatic: null,
  ),
  'toString': ta.MethodDescriptor(
    name: 'toString',
    isStatic: false,
    isAbstract: false,
    isOperator: false,
    returnTypeQualifiedName: 'dart:core.String',
    declaringClassQualifiedName: null,
    typeParameters: const [],
    parameters: const [],
    annotations: [
ta.AnnotationDescriptor(name: 'override',qualifiedName: 'dart:core.override',positionalArguments: <Object?>[],namedArguments: const <String, Object?>{},)
],
    invokeOn: (Object instance, List<dynamic> positional, Map<Symbol, dynamic> named) => Function.apply((instance as lib0.User).toString, positional, named),
    invokeStatic: null,
  ),
  'baseFields': ta.MethodDescriptor(
    name: 'baseFields',
    isStatic: false,
    isAbstract: false,
    isOperator: false,
    returnTypeQualifiedName: 'dart:core.Map',
    declaringClassQualifiedName: 'package:reflector_reflection_advanced_sample/store.dart.Entity',
    typeParameters: const [],
    parameters: const [],
    annotations: const [],
    invokeOn: (Object instance, List<dynamic> positional, Map<Symbol, dynamic> named) => Function.apply((instance as lib0.User).baseFields, positional, named),
    invokeStatic: null,
  ),
  },
  staticMethods: const {},
  fields: <String, ta.FieldDescriptor>{
  'name': ta.FieldDescriptor(
    name: 'name',
    typeQualifiedName: 'dart:core.String',
    isStatic: false,
    isFinal: false,
    isConst: false,
    declaringClassQualifiedName: null,
    annotations: const [],
    getInstance: (Object instance) => (instance as lib0.User).name,
    setInstance: (Object instance, Object? value) { (instance as lib0.User).name = value as dynamic; return null; },
    getStatic: null,
    setStatic: null,
  ),
  'email': ta.FieldDescriptor(
    name: 'email',
    typeQualifiedName: 'dart:core.String',
    isStatic: false,
    isFinal: false,
    isConst: false,
    declaringClassQualifiedName: null,
    annotations: const [],
    getInstance: (Object instance) => (instance as lib0.User).email,
    setInstance: (Object instance, Object? value) { (instance as lib0.User).email = value as dynamic; return null; },
    getStatic: null,
    setStatic: null,
  ),
  'epochMillis': ta.FieldDescriptor(
    name: 'epochMillis',
    typeQualifiedName: 'dart:core.int',
    isStatic: false,
    isFinal: true,
    isConst: false,
    declaringClassQualifiedName: null,
    annotations: [
ta.AnnotationDescriptor(name: 'override',qualifiedName: 'dart:core.override',positionalArguments: <Object?>[],namedArguments: const <String, Object?>{},)
],
    getInstance: (Object instance) => (instance as lib0.User).epochMillis,
    setInstance: null,
    getStatic: null,
    setStatic: null,
  ),
  'loginCount': ta.FieldDescriptor(
    name: 'loginCount',
    typeQualifiedName: 'dart:core.int',
    isStatic: false,
    isFinal: false,
    isConst: false,
    declaringClassQualifiedName: null,
    annotations: const [],
    getInstance: (Object instance) => (instance as lib0.User).loginCount,
    setInstance: (Object instance, Object? value) { (instance as lib0.User).loginCount = value as dynamic; return null; },
    getStatic: null,
    setStatic: null,
  ),
  'kind': ta.FieldDescriptor(
    name: 'kind',
    typeQualifiedName: 'dart:core.String',
    isStatic: false,
    isFinal: false,
    isConst: false,
    declaringClassQualifiedName: null,
    annotations: const [],
    getInstance: (Object instance) => (instance as lib0.User).kind,
    setInstance: null,
    getStatic: null,
    setStatic: null,
  ),
  'id': ta.FieldDescriptor(
    name: 'id',
    typeQualifiedName: 'dart:core.String',
    isStatic: false,
    isFinal: true,
    isConst: false,
    declaringClassQualifiedName: 'package:reflector_reflection_advanced_sample/store.dart.Entity',
    annotations: const [],
    getInstance: (Object instance) => (instance as lib0.User).id,
    setInstance: null,
    getStatic: null,
    setStatic: null,
  ),
  'isoDate': ta.FieldDescriptor(
    name: 'isoDate',
    typeQualifiedName: 'dart:core.String',
    isStatic: false,
    isFinal: false,
    isConst: false,
    declaringClassQualifiedName: 'package:reflector_reflection_advanced_sample/store.dart.Timestamped',
    annotations: const [],
    getInstance: (Object instance) => (instance as lib0.User).isoDate,
    setInstance: null,
    getStatic: null,
    setStatic: null,
  ),
  },
  staticFields: <String, ta.FieldDescriptor>{
  'table': ta.FieldDescriptor(
    name: 'table',
    typeQualifiedName: 'dart:core.String',
    isStatic: true,
    isFinal: false,
    isConst: true,
    declaringClassQualifiedName: null,
    annotations: const [],
    getInstance: null,
    setInstance: null,
    getStatic: () => lib0.User.table,
    setStatic: null,
  ),
  },
  getters: const {},
  staticGetters: const {},
  setters: const {},
  staticSetters: const {},
  superclassQualifiedName: 'package:reflector_reflection_advanced_sample/store.dart.Entity',
  interfaceQualifiedNames: <String>['package:reflector_reflection_advanced_sample/store.dart.Auditable'],
  mixinQualifiedNames: <String>['package:reflector_reflection_advanced_sample/store.dart.Timestamped'],
  appliedExtensionQualifiedNames: const [],
  constructors: <String, ta.ConstructorDescriptor>{
    'new': ta.ConstructorDescriptor(
      name: 'new',
      isFactory: false,
      parameters: [
ta.ParameterDescriptor(name: 'id',typeQualifiedName: 'dart:core.String',isRequired: true,isNamed: true,isPositional: false,hasDefaultValue: false,defaultValue: null,annotations: const [],),
ta.ParameterDescriptor(name: 'name',typeQualifiedName: 'dart:core.String',isRequired: true,isNamed: true,isPositional: false,hasDefaultValue: false,defaultValue: null,annotations: const [],),
ta.ParameterDescriptor(name: 'email',typeQualifiedName: 'dart:core.String',isRequired: true,isNamed: true,isPositional: false,hasDefaultValue: false,defaultValue: null,annotations: const [],),
ta.ParameterDescriptor(name: 'epochMillis',typeQualifiedName: 'dart:core.int',isRequired: true,isNamed: true,isPositional: false,hasDefaultValue: false,defaultValue: null,annotations: const [],)
],
      annotations: const [],
      invoke: (List<dynamic> positional, Map<Symbol, dynamic> named) => Function.apply(lib0.User.new, positional, named),
    ),
  },
  isInstance: (Object instance) => instance is lib0.User,
),
};
final _enums = <String, ta.MemberContainerDescriptor>{
'package:reflector_reflection_advanced_sample/store.dart.Channel': ta.MemberContainerDescriptor(
  kind: ta.TypeKind.enumType,
  name: 'Channel',
  qualifiedName: 'package:reflector_reflection_advanced_sample/store.dart.Channel',
  libraryUri: 'package:reflector_reflection_advanced_sample/store.dart',
  package: 'reflector_reflection_advanced_sample',
  annotations: const [],
  typeParameters: const [],
  methods: const {},
  staticMethods: const {},
  fields: const {},
  staticFields: const {},
  getters: const {},
  staticGetters: const {},
  setters: const {},
  staticSetters: const {},
),
};
final _mixins = <String, ta.MemberContainerDescriptor>{
'package:reflector_reflection_advanced_sample/store.dart.Timestamped': ta.MemberContainerDescriptor(
  kind: ta.TypeKind.mixinType,
  name: 'Timestamped',
  qualifiedName: 'package:reflector_reflection_advanced_sample/store.dart.Timestamped',
  libraryUri: 'package:reflector_reflection_advanced_sample/store.dart',
  package: 'reflector_reflection_advanced_sample',
  annotations: const [],
  typeParameters: const [],
  methods: const {},
  staticMethods: const {},
  fields: <String, ta.FieldDescriptor>{
  'epochMillis': ta.FieldDescriptor(
    name: 'epochMillis',
    typeQualifiedName: 'dart:core.int',
    isStatic: false,
    isFinal: false,
    isConst: false,
    declaringClassQualifiedName: null,
    annotations: const [],
    getInstance: (Object instance) => (instance as lib0.Timestamped).epochMillis,
    setInstance: null,
    getStatic: null,
    setStatic: null,
  ),
  'isoDate': ta.FieldDescriptor(
    name: 'isoDate',
    typeQualifiedName: 'dart:core.String',
    isStatic: false,
    isFinal: false,
    isConst: false,
    declaringClassQualifiedName: null,
    annotations: const [],
    getInstance: (Object instance) => (instance as lib0.Timestamped).isoDate,
    setInstance: null,
    getStatic: null,
    setStatic: null,
  ),
  },
  staticFields: const {},
  getters: const {},
  staticGetters: const {},
  setters: const {},
  staticSetters: const {},
),
};
final _extensions = <String, ta.ExtensionDescriptor>{
};
final _extensionTypes = <String, ta.MemberContainerDescriptor>{
};
final _typeAliases = <String, ta.TypeAliasDescriptor>{
};
final _globals = <String, ta.GlobalDescriptor>{
};
final reflectionApi = ta.ReflectionApi(
  classesByQualifiedName: _classes,
  enumsByQualifiedName: _enums,
  mixinsByQualifiedName: _mixins,
  extensionsByQualifiedName: _extensions,
  extensionTypesByQualifiedName: _extensionTypes,
  typeAliasesByQualifiedName: _typeAliases,
  globalsByQualifiedName: _globals,
);
